sudo: false
cache: bundler
language: ruby

rvm:
  - 2.3.0
  - 2.2.4
  - 2.2.2
  - ruby
  - ruby-head
  - jruby
  - jruby-19mode
  - jruby-head
  - rbx-2
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: rbx-head

notifications:
  email:
    recipients:
      - johncwang@gmail.com
    on_success: always
    on_failure: always
  webhooks:
    - https://zapier.com/hooks/catch/2y1h4a/
